const words = [
    "Arya Stark",
    "Sandor Clegane",
    "Tywin Lannister",
    "Lord of Light",
    "Red Wedding",
    "Trial By Combat",
    "Castle Black",
    "The Nights Watch",
    "White Walkers",
    "Iron Throne",
    "High Garden",
    "Winterfell",
    "Oberyn Martel",
    "The Mountain",
    "Dragon Glass",
    "Longclaw",
    "Tormund Giantsbane",
    "Kings Landing",
    "Euron Greyjoy",
    "The Golden Company",
    "Sansa Stark",
    "Ser Bronn Of The Blackwater",
    "Littlefinger",
    "King Joffrey",
    "The Three Eyed Raven",
    "Valyrian Steel",
    "Tyrion Lannister",
    "Ser Arthur Dayne",
    "The Sword Of The Morning",
    "Rhaegar Targaryen",
    "Dothrakis",
    "Jorah Mormont",
    "Theon Greyjoy",
    "Needle",
    "Direwolf",
    "Casterly Rock",
    "Eddard Stark",
    "Ramsey Snow",
    "The Battle Of The Bastards",
    "Stannis Baratheon",
    "Thoros Of Myr",
    "Beric Dondarrion",
    "The Brotherhood Without Banners",
    "Grand Maester Pycelle",
    "Jamie Lannister",
    "Cersei Lannister",
    "A Song Of Ice And Fire",
    "The Night King",
    "The High Sparrow",
    "Ser Barristan Selmy",
    "Khal Drogo",
    "Brienne Of Tarth"
];

function getWord() {
    return words[Math.floor(Math.random() * words.length)].toUpperCase();
}

export { getWord };